import { useState } from "react";

export default function App() {
  return (
    <div className="App">
      <FlashCards />
    </div>
  );
}
const countriesArray = [
  { id: 1, country: "Afghanistan", capital: "Kabul" },
  { id: 2, country: "Albania", capital: "Tirana" },
  { id: 3, country: "Algeria", capital: "Algiers" },
  { id: 4, country: "Andorra", capital: "Andorra la Vella" },
  { id: 5, country: "Angola", capital: "Luanda" },
  { id: 6, country: "Antigua and Barbuda", capital: "St. John's" },
  { id: 7, country: "Argentina", capital: "Buenos Aires" },
  { id: 8, country: "Armenia", capital: "Yerevan" },
  { id: 9, country: "Australia", capital: "Canberra" },
  { id: 10, country: "Austria", capital: "Vienna" },
  { id: 11, country: "Azerbaijan", capital: "Baku" },
  { id: 12, country: "Bahamas", capital: "Nassau" },
  { id: 13, country: "Bahrain", capital: "Manama" },
  { id: 14, country: "Bangladesh", capital: "Dhaka" },
  { id: 15, country: "Barbados", capital: "Bridgetown" },
  { id: 16, country: "Belarus", capital: "Minsk" },
  { id: 17, country: "Belgium", capital: "Brussels" },
  { id: 18, country: "Belize", capital: "Belmopan" },
  { id: 19, country: "Benin", capital: "Porto-Novo" },
  { id: 20, country: "Bhutan", capital: "Thimphu" },
  { id: 21, country: "Bolivia", capital: "La Paz (administrative), Sucre (constitutional)" },
  { id: 22, country: "Bosnia and Herzegovina", capital: "Sarajevo" },
  { id: 23, country: "Botswana", capital: "Gaborone" },
  { id: 24, country: "Brazil", capital: "Brasília" },
  { id: 25, country: "Brunei", capital: "Bandar Seri Begawan" },
  { id: 26, country: "Bulgaria", capital: "Sofia" },
  { id: 27, country: "Burkina Faso", capital: "Ouagadougou" },
  { id: 28, country: "Burundi", capital: "Gitega" },
  { id: 29, country: "Cabo Verde", capital: "Praia" },
  { id: 30, country: "Cambodia", capital: "Phnom Penh" },
  { id: 31, country: "Cameroon", capital: "Yaoundé" },
  { id: 32, country: "Canada", capital: "Ottawa" },
  { id: 33, country: "Central African Republic", capital: "Bangui" },
  { id: 34, country: "Chad", capital: "N'Djamena" },
  { id: 35, country: "Chile", capital: "Santiago" },
  { id: 36, country: "China", capital: "Beijing" },
  { id: 37, country: "Colombia", capital: "Bogotá" },
  { id: 38, country: "Comoros", capital: "Moroni" },
  { id: 39, country: "Congo (Congo-Brazzaville)", capital: "Brazzaville" },
  { id: 40, country: "Costa Rica", capital: "San José" },
  { id: 41, country: "Croatia", capital: "Zagreb" },
  { id: 42, country: "Cuba", capital: "Havana" },
  { id: 43, country: "Cyprus", capital: "Nicosia" },
  { id: 44, country: "Czechia (Czech Republic)", capital: "Prague" },
  { id: 45, country: "Democratic Republic of the Congo (Congo-Kinshasa)", capital: "Kinshasa" },
  { id: 46, country: "Denmark", capital: "Copenhagen" },
  { id: 47, country: "Djibouti", capital: "Djibouti" },
  { id: 48, country: "Dominica", capital: "Roseau" },
  { id: 49, country: "Dominican Republic", capital: "Santo Domingo" },
  { id: 50, country: "Ecuador", capital: "Quito" },
  { id: 51, country: "Egypt", capital: "Cairo" },
  { id: 52, country: "El Salvador", capital: "San Salvador" },
  { id: 53, country: "Equatorial Guinea", capital: "Malabo" },
  { id: 54, country: "Eritrea", capital: "Asmara" },
  { id: 55, country: "Estonia", capital: "Tallinn" },
  { id: 56, country: "Eswatini (Swaziland)", capital: "Mbabane (administrative), Lobamba (royal and legislative)" },
  { id: 57, country: "Ethiopia", capital: "Addis Ababa" },
  { id: 58, country: "Fiji", capital: "Suva" },
  { id: 59, country: "Finland", capital: "Helsinki" },
  { id: 60, country: "France", capital: "Paris" },
  { id: 61, country: "Gabon", capital: "Libreville" },
  { id: 62, country: "Gambia", capital: "Banjul" },
  { id: 63, country: "Georgia", capital: "Tbilisi" },
  { id: 64, country: "Germany", capital: "Berlin" },
  { id: 65, country: "Ghana", capital: "Accra" },
  { id: 66, country: "Greece", capital: "Athens" },
  { id: 67, country: "Grenada", capital: "St. George's" },
  { id: 68, country: "Guatemala", capital: "Guatemala City" },
  { id: 69, country: "Guinea", capital: "Conakry" },
  { id: 70, country: "Guinea-Bissau", capital: "Bissau" },
  { id: 71, country: "Guyana", capital: "Georgetown" },
  { id: 72, country: "Haiti", capital: "Port-au-Prince" },
  { id: 73, country: "Holy See (Vatican City)", capital: "Vatican City" },
  { id: 74, country: "Honduras", capital: "Tegucigalpa" },
  { id: 75, country: "Hungary", capital: "Budapest" },
  { id: 76, country: "Iceland", capital: "Reykjavik" },
  { id: 77, country: "India", capital: "New Delhi" },
  { id: 78, country: "Indonesia", capital: "Jakarta" },
  { id: 79, country: "Iran", capital: "Tehran" },
  { id: 80, country: "Iraq", capital: "Baghdad" },
  { id: 81, country: "Ireland", capital: "Dublin" },
  { id: 82, country: "Israel", capital: "Jerusalem (claimed), Tel Aviv (international recognition)" },
  { id: 83, country: "Italy", capital: "Rome" },
  { id: 84, country: "Jamaica", capital: "Kingston" },
  { id: 85, country: "Japan", capital: "Tokyo" },
  { id: 86, country: "Jordan", capital: "Amman" },
  { id: 87, country: "Kazakhstan", capital: "Nur-Sultan (formerly Astana)" },
  { id: 88, country: "Kenya", capital: "Nairobi" },
  { id: 89, country: "Kiribati", capital: "South Tarawa" },
  { id: 90, country: "Kuwait", capital: "Kuwait City" },
  { id: 91, country: "Kyrgyzstan", capital: "Bishkek" },
  { id: 92, country: "Laos", capital: "Vientiane" },
  { id: 93, country: "Latvia", capital: "Riga" },
  { id: 94, country: "Lebanon", capital: "Beirut" },
  { id: 95, country: "Lesotho", capital: "Maseru" },
  { id: 96, country: "Liberia", capital: "Monrovia" },
  { id: 97, country: "Libya", capital: "Tripoli" },
  { id: 98, country: "Liechtenstein", capital: "Vaduz" },
  { id: 99, country: "Lithuania", capital: "Vilnius" },
  { id: 100, country: "Luxembourg", capital: "Luxembourg City" },
  { id: 101, country: "Madagascar", capital: "Antananarivo" },
  { id: 102, country: "Malawi", capital: "Lilongwe" },
  { id: 103, country: "Malaysia", capital: "Kuala Lumpur (official), Putrajaya (administrative)" },
  { id: 104, country: "Maldives", capital: "Malé" },
  { id: 105, country: "Mali", capital: "Bamako" },
  { id: 106, country: "Malta", capital: "Valletta" },
  { id: 107, country: "Marshall Islands", capital: "Majuro" },
  { id: 108, country: "Mauritania", capital: "Nouakchott" },
  { id: 109, country: "Mauritius", capital: "Port Louis" },
  { id: 110, country: "Mexico", capital: "Mexico City" },
  { id: 111, country: "Micronesia", capital: "Palikir" },
  { id: 112, country: "Moldova", capital: "Chisinau" },
  { id: 113, country: "Monaco", capital: "Monaco" },
  { id: 114, country: "Mongolia", capital: "Ulaanbaatar" },
  { id: 115, country: "Montenegro", capital: "Podgorica" },
  { id: 116, country: "Morocco", capital: "Rabat" },
  { id: 117, country: "Mozambique", capital: "Maputo" },
  { id: 118, country: "Myanmar (formerly Burma)", capital: "Naypyidaw" },
  { id: 119, country: "Namibia", capital: "Windhoek" },
  { id: 120, country: "Nauru", capital: "Yaren" },
  { id: 121, country: "Nepal", capital: "Kathmandu" },
  { id: 122, country: "Netherlands", capital: "Amsterdam (constitutional), The Hague (seat of government)" },
  { id: 123, country: "New Zealand", capital: "Wellington" },
  { id: 124, country: "Nicaragua", capital: "Managua" },
  { id: 125, country: "Niger", capital: "Niamey" },
  { id: 126, country: "Nigeria", capital: "Abuja" },
  { id: 127, country: "North Korea", capital: "Pyongyang" },
  { id: 128, country: "North Macedonia", capital: "Skopje" },
  { id: 129, country: "Norway", capital: "Oslo" },
  { id: 130, country: "Oman", capital: "Muscat" },
  { id: 131, country: "Pakistan", capital: "Islamabad" },
  { id: 132, country: "Palau", capital: "Ngerulmud" },
  { id: 133, country: "Palestine State", capital: "Jerusalem (claimed), Ramallah (administrative)" },
  { id: 134, country: "Panama", capital: "Panama City" },
  { id: 135, country: "Papua New Guinea", capital: "Port Moresby" },
  { id: 136, country: "Paraguay", capital: "Asunción" },
  { id: 137, country: "Peru", capital: "Lima" },
  { id: 138, country: "Philippines", capital: "Manila" },
  { id: 139, country: "Poland", capital: "Warsaw" },
  { id: 140, country: "Portugal", capital: "Lisbon" },
  { id: 141, country: "Qatar", capital: "Doha" },
  { id: 142, country: "Romania", capital: "Bucharest" },
  { id: 143, country: "Russia", capital: "Moscow" },
  { id: 144, country: "Rwanda", capital: "Kigali" },
  { id: 145, country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { id: 146, country: "Saint Lucia", capital: "Castries" },
  { id: 147, country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { id: 148, country: "Samoa", capital: "Apia" },
  { id: 149, country: "San Marino", capital: "San Marino" },
  { id: 150, country: "Sao Tome and Principe", capital: "São Tomé" },
  { id: 151, country: "Saudi Arabia", capital: "Riyadh" },
  { id: 152, country: "Senegal", capital: "Dakar" },
  { id: 153, country: "Serbia", capital: "Belgrade" },
  { id: 154, country: "Seychelles", capital: "Victoria" },
  { id: 155, country: "Sierra Leone", capital: "Freetown" },
  { id: 156, country: "Singapore", capital: "Singapore" },
  { id: 157, country: "Slovakia", capital: "Bratislava" },
  { id: 158, country: "Slovenia", capital: "Ljubljana" },
  { id: 159, country: "Solomon Islands", capital: "Honiara" },
  { id: 160, country: "Somalia", capital: "Mogadishu" },
  { id: 161, country: "South Africa", capital: "Pretoria (administrative), Bloemfontein (judicial), Cape Town (legislative)" },
  { id: 162, country: "South Korea", capital: "Seoul" },
  { id: 163, country: "South Sudan", capital: "Juba" },
  { id: 164, country: "Spain", capital: "Madrid" },
  { id: 165, country: "Sri Lanka", capital: "Colombo" },
  { id: 166, country: "Sudan", capital: "Khartoum" },
  { id: 167, country: "Suriname", capital: "Paramaribo" },
  { id: 168, country: "Sweden", capital: "Stockholm" },
  { id: 169, country: "Switzerland", capital: "Bern" },
  { id: 170, country: "Syria", capital: "Damascus" },
  { id: 171, country: "Tajikistan", capital: "Dushanbe" },
  { id: 172, country: "Tanzania", capital: "Dodoma (official), Dar es Salaam (administrative)" },
  { id: 173, country: "Thailand", capital: "Bangkok" },
  { id: 174, country: "Timor-Leste (East Timor)", capital: "Dili" },
  { id: 175, country: "Togo", capital: "Lomé" },
  { id: 176, country: "Tonga", capital: "Nukuʻalofa" },
  { id: 177, country: "Trinidad and Tobago", capital: "Port of Spain" },
  { id: 178, country: "Tunisia", capital: "Tunis" },
  { id: 179, country: "Turkey", capital: "Ankara" },
  { id: 180, country: "Turkmenistan", capital: "Ashgabat" },
  { id: 181, country: "Tuvalu", capital: "Funafuti" },
  { id: 182, country: "Uganda", capital: "Kampala" },
  { id: 183, country: "Ukraine", capital: "Kyiv (Kiev)" },
  { id: 184, country: "United Arab Emirates", capital: "Abu Dhabi" },
  { id: 185, country: "United Kingdom", capital: "London" },
  { id: 186, country: "United States of America", capital: "Washington, D.C." },
  { id: 187, country: "Uruguay", capital: "Montevideo" },
  { id: 188, country: "Uzbekistan", capital: "Tashkent" },
  { id: 189, country: "Vanuatu", capital: "Port Vila" },
  { id: 190, country: "Venezuela", capital: "Caracas" },
  { id: 191, country: "Vietnam", capital: "Hanoi" },
  { id: 192, country: "Yemen", capital: "Sana'a" },
  { id: 193, country: "Zambia", capital: "Lusaka" },
  { id: 194, country: "Zimbabwe", capital: "Harare" }
];


function FlashCards() {
  const [selectedId, setSelectedId] = useState(null)

  function handleClick (id){
    setSelectedId(id !== selectedId ? id : null)
  }
  return (
    <div className="flashcards">
      {countriesArray.map((item) => (
        <div key={item.id} onClick={ () => handleClick(item.id)} style={ item.id === selectedId ? {backgroundColor: "red"} : {backgroundColor: "#f7f7f7"}}>
          <p>{item.id === selectedId ? item.capital : item.country}</p>

        </div>
      )
      )}
    </div>
  )
}
